export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const SET_TEXT = 'SET_TEXT'
export const SET_OPEN_TOP_MODAL = "SET_OPEN_TOP_MODAL"
export const SET_CLOSE_TOP_MODAL = "SET_CLOSE_TOP_MODAL"
export const SAVE_INFO_USER = "SAVE_INFO_USER"
export const REFESH_TOKEN_SUCCESS="REFESH_TOKEN_SUCCESS"
export const LOGOUT="LOGOUT"
export const UPDATE_INFO_SINGLE="UPDATE_INFO_SINGLE"
export const SAVE_AGE="SAVE_AGE"
export const LOADING="LOADING"
export const LOADING_SUCCESS="LOADING_SUCCESS"

export const SET_IS_HAVE_NEW_NOTI = "SET_IS_HAVE_NEW_NOTI"
export const SET_CLEAR_NOTI = "SET_CLEAR_NOTI"

// vé mời
export const SET_BADGE_TICKET   = "SET_BADGE_TICKET"
export const SET_BADGE_TICKET_INC   = "SET_BADGE_TICKET_INC"
export const CLEAR_BADGE_TICKET = "CLEAR_BADGE_TICKET"

// lời mời
export const SET_BADGE_INVITATION   = "SET_BADGE_INVITATION"
export const SET_BADGE_INVITATION_INC   = "SET_BADGE_INVITATION_INC"
export const CLEAR_BADGE_INVITATION = "CLEAR_BADGE_INVITATION"
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS"
export const UPDATE_CART = "UPDATE_CART"

