module.exports = {
  // COMMON SCREEN
  COMMONSCREEN: 'CommonScreen',
  SPLASH_SCREEN: 'SplashScreen',
  ModalInsertConcept: "ModalInsertConcept",

  //USER AUTH SCREEN
  Login: 'Login',
  LoginPhone: 'LoginPhone',
  SignUp: 'SignUp',
  SignUpName: "SignUpName",
  SignUpBirthday: "SignUpBirthday",
  SignUpEmail: "SignUpEmail",
  SignUpPickImage: "SignUpPickImage",
  SignUpListImage: "SignUpListImage",
  SignUpPassword: "SignUpPassword",
  SignUpLocation: "SignUpLocation",
  SignUpDone: "SignUpDone",

  SignUpInfoDetail: 'SignUpInfoDetail',
  VerifyCodeEmail: 'VerifyCodeEmail',
  SignUpSuccess: 'SignUpSuccess',
  ForgotPass: 'ForgotPass',
  LoginWithPassword: 'LoginWithPassword',
  ForgotPassViaEmail: 'ForgotPassViaEmail',
  /**
   * ACCOUNT of USER
   */
  USER_SCREEN: 'USER_SCREEN',
  /**
   * Những screen như đăng ký, đăng nhập, quên mật khẩu, ...
   */
  GUEST_SCREEN: 'GUEST_SCREEN',
  /**
  * MAIN SCREEN
  * (là KEY chứa các tab)
  */
  MAIN_SCREEN: 'MainScreen',
  /**
  * TAB BOTTOM SCREEN
  */
  TAB_BOTTOM_HOME: 'Trang chủ',
  TAB_BOTTOM_CONCEPT: 'TAB_CONCEPT',
  TAB_BOTTOM_ADD_BUTTON: 'ADD_BUTTON',
  TAB_BOTTOM_CHAT: 'TAB_CHAT',
  TAB_BOTTOM_USER: 'Cá nhân',
  TAB_BOTTOM_CATEGORY:'Danh mục',
  TAB_BOTTOM_SEARCH:'Tìm kiếm',
  //
  SETTINGS_SCREEN: 'SETTING_SCREEN',
  ACCOUNT_INFO: 'ACCOUNT_INFO',

  NOTIFICATION: 'NOTIFICATION',
  VVIP: "VVIP",
  DATE_INFO_SCREEN: 'DATE_INFO_SCREEN',
  DATE_INFO: 'DATE_INFO',
  JOIN: 'JOIN',
  CONFIRM_INVITATION: "CONFIRM_INVITATION",
  CHATTING: "CHATTING",
  CHATTING_TAB_BAR_MAIN: "CHATTING_TAB_BAR_MAIN", // not Test
  CHATTING_SEARCH: "CHATTING_SEARCH",
  CHATTING_SCREEN: "CHATTING_SCREEN",
  CHATTING_LIST_REQUEST_TO_JOIN: 'CHATTING_LIST_REQUEST_TO_JOIN',
  LIST_JOIN: "LIST_JOIN",
  LISTJOIN_SCREEN: "LISTJOIN_SCREEN",
  CHOICE_PEOPLE: "CHOICE_PEOPLE",
  CONCEPT_SCREEN: "CONCEPT_SCREEN",
  MAIN_CONCEPT: "MAIN_CONCEPT",
  INFO_USER_JOIN: "INFO_USER_JOIN",
  USER: "USER",
  CONFIRM_USER: "CONFIRM_USER",
  FOR_PARTNER: "FOR_PARTNER",
  HISTORY_REWARD_POINT: "HISTORY_REWARD_POINT",
  EDIT_USER: "EDIT_USER",
  EDIT_USER_NAME: "EDIT_USER_NAME",
  EDIT_USER_INTRODUCE: "EDIT_USER_INTRODUCE",
  EDIT_USER_EXPECTED: "EDIT_USER_EXPECTED",
  EDIT_CONCEPT: "EDIT_CONCEPT",
  MAIN_CONCEPT_DEMO: "MAIN_CONCEPT_DEMO",
  CONCEPT_DEMO_SCREEN: "CONCEPT_DEMO_SCREEN",
  LIBRARY_CONCEPT: "LIBRARY_CONCEPT",
  TIPS_CONCEPT: "TIPS_CONCEPT",
  DETAILS_LIBRARY_CONCEPT: "DETAILS_LIBRARY_CONCEPT",
  LIBRARY_ADDRESS_CONCEPT: "LIBRARY_ADDRESS_CONCEPT",
  DETAILS_LIBRARY_ADDRESS_CONCEPT: 'DETAILS_LIBRARY_ADDRESS_CONCEPT',
  INFO_DETAILS_LIBRARY_CONCEPT: "INFO_DETAILS_LIBRARY_CONCEPT",
  DETAILS_TIPS_CONCEPT: "DETAILS_TIPS_CONCEPT",
  OLD_CONCEPTS: "OLD_CONCEPTS",
  LIST_RECOMEND_USER_JOINCONCEPT: 'LIST_RECOMEND_USER_JOINCONCEPT',
  FEEDBACK_CONCEPT: "FEEDBACK_CONCEPT",
  LIST_USERS_TO_SEND_INVITATION: 'LIST_USERS_TO_SEND_INVITATION',
  LIST_PARTICIPANT: "LIST_PARTICIPANT",
  LIST_USERS_LIKED: 'LIST_USERS_LIKED',
  LOG_OUT: 'LOG_OUT',
  ME_SEND_AND_SEND_ME: "ME_SEND_AND_SEND_ME",

  DRAW_REWARD_POINTS: "DRAW_REWARD_POINTS",
  REQUEST_PROCESSING_STATUS: "REQUEST_PROCESSING_STATUS",
  MODAL_RECOMEND_USER_JOIN_CONCEPT: 'MODAL_RECOMEND_USER_JOIN_CONCEPT',
  MODAL_RECOMEND_USER_JOIN: 'MODAL_RECOMEND_USER_JOIN_CONCEPT',
  OPTION_CONFIRM_USER: 'OPTION_CONFIRM_USER',
  CONFIRM_PHONE_NUMBER: "CONFIRM_PHONE_NUMBER",
  LIST_TICKET_I_HAVE: 'LIST_TICKET_I_HAVE',
  SET_PASSWORD: 'SET_PASSWORD',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SHOPPING: 'SHOPPING',
  UPGRAGE_ACCOUNT: 'UPGRAGE_ACCOUNT',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  PAYMENT_HISTORY: 'PAYMENT_HISTORY'
};
